### ISSUE TITLE
Some kind of filtering Required!

### ISSUE THREAD

**Issue by rmtucker** [uvjim/rpi_waveshare_ups#8]
Hmm my ups hat is dropping to -183ma during normal fully charged situations.
Just wondering if some kind of filtering can be applied to help mitigate the downward spikey readings?
![Screenshot from 2024-07-11 15-27-48](https://github.com/uvjim/rpi_waveshare_ups/assets/6954079/6b3a50c4-983d-41f9-9cf8-2fc1384576be)
I have the config set to -150ma but it still triggers Battery state = "Powering the Pi" every hour or two.
The larger spike is me testing the ups

**Comment by uvjim** [comment]
Hi, sorry for the extremely late reply.  There isn't anything currently in there integration to manage this.  I must admit I don't actively monitor the UPS so I have no idea if I'm seeing something similar.  For me as long as it continues to power the Pi when the main power disappears that's all I'm interested in.

I only really wrote the integration so that I could detect when power switches to the UPS for a period of time so that I could gracefully shutdown.  In fact, I don't think I ever got around to building the automation and nor has the power in the house cut for long enough to cause a problem.

**Comment by rmtucker** [comment]
Thank you for your reply
I must admit,i have had no power cuts here to see it in action either.
And The current reading is pretty useless anyway other than it keeps triggering charge/not charging,but really it is of no consequence

**Comment by uvjim** [comment]
If it's any help, here's mine since midnight.  As you can see there are troughs.  As you say, short of it changing the state of a `binary_sensor` it isn't really doing much else.  If you wanted to build an automation you'd probably hold it in that state for a period of time, e.g. when the binary sensor is on for X minutes/hours then do Y and Z.

![image](https://github.com/user-attachments/assets/9d7750cf-bd14-4cfa-b27b-fdc76c17437a)

**Comment by rmtucker** [comment]
What interval do you have configured for retrieval of data from the ups?
Just your graph seems to be cleaner than mine.

**Comment by uvjim** [comment]
Here's my settings. 

![Screenshot_20241031_071448_Home Assistant.png](https://github.com/user-attachments/assets/375641bd-d88d-4dd3-ab65-9239d21f1853)

**Comment by uvjim** [comment]
Are you OK if I close this off? If you come up with any ideas on how I can smooth this out for you, I'm all ears.
